
console.log("=========================Assignment Number-2===========================");
console.log("=========================First Step=================================","\n");
var bankName;
console.log("Before initialization:",bankName, "(Type Data type):",typeof bankName);
bankName='SBI Bank';
console.log("After initialization:",bankName,"(Type of Data):",typeof bankName);
console.log("=========================Second Step=================================","\n");
var marks="90%";
console.log("Total %:",marks,"(Type of Data):",typeof marks);
console.log("=========================Third Step=================================","\n");
var isWorking;
console.log("Before initialization:",isWorking,"(type of data):", typeof isWorking);
isWorking=true;
console.log("After initialization:",isWorking,"(Type of data):",typeof isWorking);
console.log("=========================Third Step=================================","\n");
var totalCount="Hundred and Seven";
console.log("Total count is:",totalCount,"(type of data):", typeof totalCount);
totalCount=107;
console.log("Updated count is:",totalCount,"(Type of data):", typeof totalCount);
console.log("=========================Finished all Step===========================");